# docker-compose.yml
version: "3.9"

volumes:
  duckdb_data:
  grafana_data:


services:
  prepare: 
    image: alpine:latest
    command: ["mkdir", "-p", "/work/data", "&&", "mkdir", "-p", "/work/out"]
    volumes:
      - .:/work:z
    restart: "no"
    profiles: ["sync"]

  collector:
    build:
      context: .
      dockerfile: docker/Dockerfile.collector
    env_file: .env
    volumes:
      - ./src:/app/src:z
      - ./data:/app/data:z
      - ./db:/app/db:ro,z
    restart: "no"
    depends_on:
      prepare:
        condition: service_completed_successfully
    profiles: ["sync"]

  db-create:
    image: datacatering/duckdb:v1.3.2
    working_dir: /work
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - "rm -f /work/out/github_org.db && /duckdb /work/out/github_org.db < /work/db/create_tables.sql"
    volumes:
      - ./data:/work/data:z
      - ./out:/work/out:z
      - ./db/create_tables.sql:/work/db/create_tables.sql:ro
    depends_on:
      collector:
        condition: service_completed_successfully
      prepare:
        condition: service_completed_successfully
    restart: "no"
    profiles: ["sync"]

  ui:
    image: datacatering/duckdb:v1.3.2
    working_dir: /work
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - "/duckdb /work/out/github_org.db -cmd 'call start_ui_server()'"
    volumes:
      - ./out:/work/out:z
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    profiles: ["ui"]

  ui-after-sync:
    image: datacatering/duckdb:v1.3.2
    working_dir: /work
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - "/duckdb /work/out/github_org.db -cmd 'call start_ui_server()'"
    volumes:
      - ./out:/work/out:z
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      db-create:
        condition: service_completed_successfully
    profiles: ["sync"]




