# docker-compose.yml
version: "3.9"

volumes:
  duckdb_data:
  grafana_data:


services:
  collector:
    build:
      context: .
      dockerfile: docker/Dockerfile.collector
    env_file: .env
    volumes:
      - ./data:/app/data:z
      - ./db:/app/db:ro,z
    restart: "no"

  db-create:
    image: datacatering/duckdb:v1.3.2
    working_dir: /work
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - "rm -f /work/out/github_org.db && /duckdb /work/out/github_org.db < /work/db/create_tables.sql"
    volumes:
      - ./data:/work/data:z
      - ./out:/work/out:z
      - ./db/create_tables.sql:/work/db/create_tables.sql:ro
    depends_on:
      collector:
        condition: service_completed_successfully
    restart: "no"

  ui:
    image: datacatering/duckdb:v1.3.2
    working_dir: /work
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - "/duckdb /work/out/github_org.db -ui"
    volumes:
      - ./out:/work/out:z
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped



